stem/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls import url
from django.contrib.admin.views.decorators import staff_member_required
from . import views as user_views#update
from .views import StudentCreateView, StudentListView, StudentDetailView, pdf, register
from django.conf import settings
from django.conf.urls.static import static


app_name = "stem"

urlpatterns = [
    #path('', views.home, name='home'),
    path('', StudentCreateView.as_view(), name='home'),
    path('manage-students/', staff_member_required(StudentListView.as_view()), name='list-students'),
    path('profile/<int:pk>/', StudentDetailView.as_view(), name='student-details'),
    path('login/', auth_views.LoginView.as_view(template_name='stem/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='stem/logout.html'), name='logout'),
    path('register/', user_views.register, name='register'),#update
    path('pdf/', user_views.pdf, name='dlpdf'),#update
    #path('new/', PostCreateView.as_view(), name='post-create'),
    #path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    #path('result/', views.search, name='result'),
    #path('new/', views.post_create, name='post-create'),
    #url(r'post/(?P<id>\d+)/$', views.post_detail, name='post-detail'),
    #url(r'^like/$', views.like_post, name='like_post'),
]

stem_enrollment/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stem.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stem/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .forms import StudentRegisterForm, UserRegisterForm
from .models import STUDENT_INFO
from django.contrib.auth.models import User
from django.views.generic import (View, DetailView, ListView, CreateView, TemplateView)
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .filter_mixin import ListFilteredMixin
from .filters import StudentFilter
from io import BytesIO
from django.http import HttpResponse
from django.template.loader import get_template
from django.shortcuts import get_object_or_404
from datetime import datetime

# Create your views here.
"""
def home(request):
    if request.method == 'POST':
        form = StudentRegisterForm(request.POST)
        formset = ImageFormset(request.POST or None, request.FILES or None)
        if form.is_valid():
            form.save()
            lrn = form.cleaned_data.get('lrn')
            messages.success(request, f'Submit Success')
            return redirect('stem:home')
    else:
        form = StudentRegisterForm()
    context={
        'form' : form,
    }
    return render(request, 'stem/enrol.html', context)"""

def pdf(request):
    user_e = request.user.id
    student = STUDENT_INFO.objects.get(student=user_e)
    context={
        'student': student,
        'user': user_e,
    }
    return render(request, 'stem/pdf_template.html', context)


class StudentCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):#update
    model = STUDENT_INFO
    form_class = StudentRegisterForm
    success_message = "Thank you!"

    def form_valid(self, form_class):#update 
        form_class.instance.student = self.request.user
        return super().form_valid(form_class)

    def get_context_data(self, *args, **kwargs):
        try:
            user = self.request.user.id
            student = STUDENT_INFO.objects.get(student=user)
            context = super(StudentCreateView, self).get_context_data(**kwargs)
            context.update({
                'student': student,
                'user': user,
            })
            return context
        except STUDENT_INFO.DoesNotExist:
            student = '0'
            user = '0'
            context = super(StudentCreateView, self).get_context_data(**kwargs)
            context.update({
                'student': student,
                'user': user,
            })
            return context


class StudentListView(LoginRequiredMixin, ListFilteredMixin, ListView):
    model = STUDENT_INFO
    template_name = 'stem/list_student.html'
    context_object_name = 'students'
    paginate_by = 30
    filter_set = StudentFilter
    def get_queryset(self):
        qs = self.model.objects.all().order_by('last_name')
        student_filter = StudentFilter(self.request.GET, queryset=qs)
        return student_filter.qs

    def get_context_data(self, *args, **kwargs):
        try:
            date_today = datetime.now().strftime("%Y")

            d1g11 = STUDENT_INFO.objects.filter(d1_walking='True', grade_level_to_enroll='Grade 11').count()
            d1g12 = STUDENT_INFO.objects.filter(d1_walking='True', grade_level_to_enroll='Grade 12').count()
            d2g11 = STUDENT_INFO.objects.filter(d1_public_commute_landwater='True', grade_level_to_enroll='Grade 11').count()
            d2g12 = STUDENT_INFO.objects.filter(d1_public_commute_landwater='True', grade_level_to_enroll='Grade 12').count()
            d3g11 = STUDENT_INFO.objects.filter(d1_family_owned_vehicle='True', grade_level_to_enroll='Grade 11').count()
            d3g12 = STUDENT_INFO.objects.filter(d1_family_owned_vehicle='True', grade_level_to_enroll='Grade 12').count()
            d4g11 = STUDENT_INFO.objects.filter(d1_school_service='True', grade_level_to_enroll='Grade 11').count()
            d4g12 = STUDENT_INFO.objects.filter(d1_school_service='True', grade_level_to_enroll='Grade 12').count()

            e1g11 = STUDENT_INFO.objects.filter(d4_cable_tv='True', grade_level_to_enroll='Grade 11').count()
            e1g12 = STUDENT_INFO.objects.filter(d4_cable_tv='True', grade_level_to_enroll='Grade 12').count()
            e2g11 = STUDENT_INFO.objects.filter(d4_noncable_tv='True', grade_level_to_enroll='Grade 11').count()
            e2g12 = STUDENT_INFO.objects.filter(d4_noncable_tv='True', grade_level_to_enroll='Grade 12').count()
            e3g11 = STUDENT_INFO.objects.filter(d4_basic_cp='True', grade_level_to_enroll='Grade 11').count()
            e3g12 = STUDENT_INFO.objects.filter(d4_basic_cp='True', grade_level_to_enroll='Grade 12').count()
            e4g11 = STUDENT_INFO.objects.filter(d4_smartphone='True', grade_level_to_enroll='Grade 11').count()
            e4g12 = STUDENT_INFO.objects.filter(d4_smartphone='True', grade_level_to_enroll='Grade 12').count()
            e5g11 = STUDENT_INFO.objects.filter(d4_tablet='True', grade_level_to_enroll='Grade 11').count()
            e5g12 = STUDENT_INFO.objects.filter(d4_tablet='True', grade_level_to_enroll='Grade 12').count()
            e6g11 = STUDENT_INFO.objects.filter(d4_radio='True', grade_level_to_enroll='Grade 11').count()
            e6g12 = STUDENT_INFO.objects.filter(d4_radio='True', grade_level_to_enroll='Grade 12').count()
            e7g11 = STUDENT_INFO.objects.filter(d4_desktop='True', grade_level_to_enroll='Grade 11').count()
            e7g12 = STUDENT_INFO.objects.filter(d4_desktop='True', grade_level_to_enroll='Grade 12').count()
            e8g11 = STUDENT_INFO.objects.filter(d4_laptop='True', grade_level_to_enroll='Grade 11').count()
            e8g12 = STUDENT_INFO.objects.filter(d4_laptop='True', grade_level_to_enroll='Grade 12').count()
            e9g11 = STUDENT_INFO.objects.filter(d4_none='True', grade_level_to_enroll='Grade 11').count()
            e9g12 = STUDENT_INFO.objects.filter(d4_none='True', grade_level_to_enroll='Grade 12').count()

            f1g11 = STUDENT_INFO.objects.filter(d6_own_mobile_data='True', grade_level_to_enroll='Grade 11').count()
            f1g12 = STUDENT_INFO.objects.filter(d6_own_mobile_data='True', grade_level_to_enroll='Grade 12').count()
            f2g11 = STUDENT_INFO.objects.filter(d6_own_broadband_internet='True', grade_level_to_enroll='Grade 11').count()
            f2g12 = STUDENT_INFO.objects.filter(d6_own_broadband_internet='True', grade_level_to_enroll='Grade 12').count()
            f3g11 = STUDENT_INFO.objects.filter(d6_computer_shop='True', grade_level_to_enroll='Grade 11').count()
            f3g12 = STUDENT_INFO.objects.filter(d6_computer_shop='True', grade_level_to_enroll='Grade 12').count()
            f4g11 = STUDENT_INFO.objects.filter(d6_other_places='True', grade_level_to_enroll='Grade 11').count()
            f4g12 = STUDENT_INFO.objects.filter(d6_other_places='True', grade_level_to_enroll='Grade 12').count()
            f5g11 = STUDENT_INFO.objects.filter(d6_none='True', grade_level_to_enroll='Grade 11').count()
            f5g12 = STUDENT_INFO.objects.filter(d6_none='True', grade_level_to_enroll='Grade 12').count()


            g1g11 = STUDENT_INFO.objects.filter(d7_ol_learning='True', grade_level_to_enroll='Grade 11').count()
            g1g12 = STUDENT_INFO.objects.filter(d7_ol_learning='True', grade_level_to_enroll='Grade 12').count()
            g2g11 = STUDENT_INFO.objects.filter(d7_tv='True', grade_level_to_enroll='Grade 11').count()
            g2g12 = STUDENT_INFO.objects.filter(d7_tv='True', grade_level_to_enroll='Grade 12').count()
            g3g11 = STUDENT_INFO.objects.filter(d7_radio='True', grade_level_to_enroll='Grade 11').count()
            g3g12 = STUDENT_INFO.objects.filter(d7_radio='True', grade_level_to_enroll='Grade 12').count()
            g4g11 = STUDENT_INFO.objects.filter(d7_modular='True', grade_level_to_enroll='Grade 11').count()
            g4g12 = STUDENT_INFO.objects.filter(d7_modular='True', grade_level_to_enroll='Grade 12').count()
            g5g11 = STUDENT_INFO.objects.filter(d7_f2f_w_modalities='True', grade_level_to_enroll='Grade 11').count()
            g5g12 = STUDENT_INFO.objects.filter(d7_f2f_w_modalities='True', grade_level_to_enroll='Grade 12').count()


            h1g11 = STUDENT_INFO.objects.filter(d8_lack_gadgets='True', grade_level_to_enroll='Grade 11').count()
            h1g12 = STUDENT_INFO.objects.filter(d8_lack_gadgets='True', grade_level_to_enroll='Grade 12').count()
            h2g11 = STUDENT_INFO.objects.filter(d8_insufficient_load='True', grade_level_to_enroll='Grade 11').count()
            h2g12 = STUDENT_INFO.objects.filter(d8_insufficient_load='True', grade_level_to_enroll='Grade 12').count()
            h3g11 = STUDENT_INFO.objects.filter(d8_unstable_internet='True', grade_level_to_enroll='Grade 11').count()
            h3g12 = STUDENT_INFO.objects.filter(d8_unstable_internet='True', grade_level_to_enroll='Grade 12').count()
            h4g11 = STUDENT_INFO.objects.filter(d8_health_conditions='True', grade_level_to_enroll='Grade 11').count()
            h4g12 = STUDENT_INFO.objects.filter(d8_health_conditions='True', grade_level_to_enroll='Grade 12').count()
            h5g11 = STUDENT_INFO.objects.filter(d8_difficulty_independent_learning='True', grade_level_to_enroll='Grade 11').count()
            h5g12 = STUDENT_INFO.objects.filter(d8_difficulty_independent_learning='True', grade_level_to_enroll='Grade 12').count()
            h6g11 = STUDENT_INFO.objects.filter(d8_con_other_activities='True', grade_level_to_enroll='Grade 11').count()
            h6g12 = STUDENT_INFO.objects.filter(d8_con_other_activities='True', grade_level_to_enroll='Grade 12').count()
            h7g11 = STUDENT_INFO.objects.filter(d8_hi_elec_consump='True', grade_level_to_enroll='Grade 11').count()

stem/templates/stem/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'stem/css/main.css' %}"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.4/jspdf.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.5.3/jspdf.debug.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Questrial&display=swap" rel="stylesheet">
    <title>Online Enrollment Form</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
      <a class="navbar-brand" href="#">
        <img src="{% static 'stem/img/cnhslogo.png' %}" width="30" height="30" alt="">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'stem:home' %}">Enrol Now</a>
          </li>
          {% if request.user.is_staff %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'stem:list-students' %}">Manage Students</a>
            </li>
          {% endif %}
            <div class="navbar-nav">
              {% if request.user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'stem:dlpdf' %}">{{ request.user.username|upper }}</a>
                <a class="nav-item nav-link" href="{% url 'stem:logout' %}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'stem:login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'stem:register' %}">Register</a>
              {% endif %}
            </div>
        </ul>
      </div>
    </nav>
    <div class="container-e">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
      {% block content %}{% endblock %}
    </div>
  </body>
    
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'stem/js/script.js' %}"></script>
</html>

stem/templates/stem/login.html
{% extends "stem/base.html" %}
    {% load crispy_forms_tags %} {% load static %} {% block content %}
    <div class="login-page">
      <div class="login-con">
        <form method="POST">
          {% csrf_token %}
          <h5>Catarman National High School</h5>
      <fieldset class="form-group">
        <div class="img-log">
            <!--<img src="{% static 'd_network/img/copypasta1.png' %}" alt="">-->
            <h3>Login</h3>
        </div>
        {{ form|crispy }}
      </fieldset>
      <div class="form-group">
        <button class="btn btn-outline-info" type="submit">Login</button>
      </div>
      <div class="border-top pt-3">
        <small class="text-muted">
          Don't Have An Account? <a class="ml-2" href="{% url 'stem:login' %}">Sign up now</a>
        </small>
      </div>
    </form>
    {% endblock %}

stem/templates/stem/logout.html
logout

stem/templates/stem/pdf_details.html
{% load crispy_forms_tags %} {% load static %} {% block content %}
    <div class="container-edit" id="target">
    <div class="form-header-e-ins-p">
      <div class="form-group col-md-12 mb-0">
        <div class="form-row">
            <div class="form-group col-md-1.5 mb-0">
                <div class="rounded-circle-edited-l">
                    <img
                    class="account-img"
                    src="{{ student.image.url }}"
                    />
                </div>
            </div>
            <div class="form-group col-md-8 mb-0">
                <b>{{ student.last_name|title }}, {{ student.first_name|title }} {{ student.middle_name|title }}</b><br>
                {{ student.track|title }} ({{ student.strand|title }}) {{ student.grade_level_to_enroll|title }} ({{ student.school_year1|title }} - {{ student.school_year2|title }})<br>
                
                {{ student.house_number_and_street|title }} {{ student.barangay|title }}, {{ student.city_municipality|title }}, {{ student.province|title }}<br>
                <!--<button type="button" class="btn btn-success" onclick="openModal();currentSlide(1)">
                  School Card
                </button>
                <button type="button" class="btn btn-success" onclick="openModal();currentSlide(1)">
                  Birth Certificate
                </button>-->
            </div>
        </div>
      </div>
    </div>
    <div class="content-login-p">
      <div class="master-login">
            <h4>A. Grade Level and School Information</h4>
            <div class="form-row">
              <div class="form-group col-md-3 pb-6  bg-sec">
                <b>School Year</b><br>
                <span>{{ student.school_year1|title }} - {{ student.school_year2|title }}</span><br>
              </div>
              <div class="form-group col-md-4 pb-6  bg-sec">
                <b>Has LRN</b><br>
                <span>{{ student.wlrn|title }}</span><br>
              </div>
              <div class="form-group col-md-5 pb-6  bg-sec">
                <b>Returning (Balik eskwela)</b><br>
                <span>{{ student.returning|title }}</span><br>
              </div>
            </div>
            <div class="form-row">
              <div class="form-group col-md-3 mb-0">
                <b>Grade level to enroll</b><br>
                <span>{{ student.grade_level_to_enroll|title }}</span><br>
                <b>Last Grade Level completed</b><br>
                <span>{{ student.last_grade_level_com|title }}</span><br>
                <b>Last School year</b><br>
                <span>{{ student.last_school_year_com|title }}</span><br>
              </div>
              <div class="form-group col-md-4 pb-6 bg-sec">
                <div class="form-row">
                  <div class="form-group col-md-8 ">
                    <b>Last School Attended</b><br>
                    <span>{{ student.last_school_attended|title }}</span><br>
                  </div>
                  <div class="form-group col-md-4 mb-0">
                    <b>School ID:</b><br>
                    <span>{{ student.school_id|title }}</span><br>
                  </div>
                </div>
                <div class="form-group col-md-13 mb-0">
                  <b>School Address:</b><br>
                  <span>{{ student.school_address|title }}</span><br>
                </div>
                <div class="form-group col-md-13 mb-0">
                  <b>School Type:</b><br>
                  <span>{{ student.school_type|title }}</span><br>
                </div>
              </div>
              <div class="form-group col-md-5 mb-0">
                <div class="form-row">
                  <div class="form-group col-md-8 mb-0">
                    <b>School to enroll:</b><br>
                    <span>{{ student.school_to_enroll_in|title }}</span><br>
                  </div>
                  <div class="form-group col-md-4 mb-0">
                    <b>School ID:</b><br>
                    <span>{{ student.school_id_to_enroll|title }}</span><br>
                  </div>
                </div>
                <div class="form-group col-md-13 mb-0">
                  <b>School Address:</b><br>
                  <span>{{ student.school_address_to_enroll|title }}</span><br>
                </div>
              </div>
              <div class="form-group col-md-12 bg-sec">
                  <div class="form-row">
                    <div class="form-group col-md-3 mb-0">
                      <b>Semester:</b><br>
                      <span>{{ student.semester|title }}</span><br>
                    </div>
                    <div class="form-group col-md-4 mb-0">
                      <b>Track:</b><br>
                      <span>{{ student.track|title }}</span><br>
                    </div>
                    <div class="form-group col-md-5 mb-0">
                      <b>Strand:</b><br>
                      <span>{{ student.strand|title }}</span><br>
                    </div>
                </div>
              </div>  
            </div>   
      </div>
    </div>   
    <div class="content-login-p">
      <div class="master-login">
            <h4>B. Student Information</h4>
            <div class="form-row bg-sec">
                <div class="form-group col-md-6 mb-0 ">
                  <b>PSA Birth Certificate No.:</b><br>
                  <span>{{ student.psa_cer_no|title }}</span><br>
                </div>
                <div class="form-group col-md-6 mb-0">
                  <b>Learners Reference Number (LRN)*:</b><br>
                  <span>{{ student.lrn|title }}</span><br>
                </div>
            </div>
            <div class="form-row bg-sec">
                <div class="form-group col-md-3 mb-0 ">
                  <b>Full name:</b><br>
                  <span>{{ student.last_name|title }}, {{ student.first_name|title }} {{ student.middle_name|title }}</span><br>
                  <b>Birthdate:</b><br>
                  <span>{{ student.birthdate|date:"d M Y" }}</span><br>
                </div>
                <div class="form-group col-md-3 mb-0 ">
                  <b>Sex:</b><br>
                  <span>{{ student.sex|title }}</span><br>
                  <b>Age:</b><br>
                  <span>{{ student.age|title }}</span><br>
                </div>
                <div class="form-group col-md-6 mb-0">
                  <b>Address:</b><br>
                  <span>{{ student.lhouse_number_and_streetrn|title }} {{ student.barangay|title }} {{ student.city_municipality|title }}, {{ student.province|title }}, {{ student.region|title }}</span><br>
                </div>
            </div>
            <div class="form-row bg-sec">
                <div class="form-group col-md-6 mb-0 ">
                  <b>Belonging to Indigenous People (IP):</b><br>
                  <span>{{ student.ip|title }} ({{ student.ip_specify|title }})</span><br>
                  <b>Mother Tounge:</b><br>
                  <span>{{ student.mother_tongue|title }}</span><br>
                  <b>Religion:</b><br>
                  <span>{{ student.religion|title }}</span><br>
                </div>
                <div class="form-group col-md-6 mb-0 ">
                  <b>For Learners with Special Education Needs</b>
                  <b>Does the learner have special education needs?</b><br>
                  <span>{{ student.special_ed_needs|title }} ({{ student.speed_needs_specify|title }})</span><br>
                  <b>Do you have any assistive technology devices available at home?</b><br>
                  <span>{{ student.technology_devices|title }} ({{ student.technology_devices_specify|title }})</span><br>
                </div>
            </div>
      </div>
    </div>
    <div class="content-login-p">
      <div class="master-login">
            <h4>C. Parent/Guardian Information</h4>
            <div class="form-row">
                <div class="form-group col-md-4 mb-0">
                  <b>Father Full name:</b><br>
                  <span>{{ student.father_full_name|title }}</span><br>
                  <b>Father Educational Attainment:</b><br>
                  <span>{{ student.father_educ_attainment|title }}</span><br>
                  <b>Father employment status</b><br>
                  <span>{{ student.father_employment_status|title }}</span><br>
                  <b>Working from home due to_ECQ:</b><br>
                  <span>{{ student.father_working_from_home_due_to_ecq|title }}</span><br>
                  <b>Father Contact No:</b><br>
                  <span>{{ student.father_contact|title }}</span><br>
                </div>
                <div class="form-group col-md-4 mb-0 bg-sec">
                  <b>Mother Full name:</b><br>
                  <span>{{ student.mother_full_name|title }}</span><br>
                  <b>Mother Educational Attainment:</b><br>
                  <span>{{ student.mother_educ_attainment|title }}</span><br>
                  <b>Mother employment status</b><br>
                  <span>{{ student.mother_employment_status|title }}</span><br>
                  <b>Working from home due to_ECQ:</b><br>
                  <span>{{ student.mother_working_from_home_due_to_ecq|title }}</span><br>
                  <b>Mother Contact No:</b><br>
                  <span>{{ student.mother_contact|title }}</span><br>
                </div>
                <div class="form-group col-md-4 mb-0">
                  <b>Guardian Full name:</b><br>
                  <span>{{ student.guardian_full_name|title }}</span><br>
                  <b>Guardian Educational Attainment:</b><br>
                  <span>{{ student.guardian_educ_attainment|title }}</span><br>
                  <b>Guardian employment status</b><br>
                  <span>{{ student.guardian_employment_status|title }}</span><br>
                  <b>Working from home due to_ECQ:</b><br>
                  <span>{{ student.guardian_working_from_home_due_to_ecq|title }}</span><br>
                  <b>Guardian Contact No:</b><br>
                  <span>{{ student.guardian_contact|title }}</span><br>
                </div>
            </div>
      </div>
    </div>
          
          <!-- Button trigger modal -->
          

          <!-- The Modal -->
          <div id="myModal" class="modal">

            <!-- The Close Button -->
            <span class="close">&times;</span>

            <!-- Modal Content (The Image) -->
            <img class="modal-content" id="img01">

            <!-- Modal Caption (Image Text) -->
            <div id="caption"></div>
          </div>
          <!--<div class="form-group">
            <button class="btn btn-primary" type="submit">Submit</button>
          </div>-->
      </div>
    </>
    </div>
    {% endblock %}

stem/templates/stem/pdf_template.html
{% extends "stem/base.html" %}
{% load crispy_forms_tags %} {% load static %} {% block content %}
    <div class="container">
        <div class="form-header-e">
        <div class="form-row">
            <div class="form-group col-md-12 mb-0">
                <img class="img-logo" src="{% static 'stem/img/cnhslogo.png' %}" alt="">
            </div>
            <div class="form-group col-md-12 mb-0">
                <h3>Welcome to Catarman National High School</h3>
            </div>
            <div class="form-group col-md-12 mb-0">
                <a class="btn btn-primary" href="{% url 'stem:student-details' student.id %}">Download Enrolment Details</a>
            </div>
        </div>
        </div>
        </div>
    </div>
    
{% endblock %}

stem/templates/stem/register.html
{% extends "stem/base.html" %}
{% load crispy_forms_tags %} {% load static %} {% block content %}
<div class="login-page">
  <div class="login-con">
    <form method="POST">
      {% csrf_token %}
      <h5>Catarman National High School</h5>
      <b>Create an account first to access the enrolment form</b>
      <fieldset class="form-group">
        {{ form|crispy }}
      </fieldset>
      <div class="form-group">
        <button class="btn btn-outline-info" type="submit">Sign Up</button>
      </div>
    </form>
    <div class="border-top pt-3">
      <small class="text-muted">
        Already Have An Account? <a class="ml-2" href="{% url 'stem:login' %}">Sign In</a>
      </small>
    </div>
  </div>
</div>
{% endblock %}